% LME Simulation Script: 2. Simulate ERP Data

% This script simulates trial-level ERP data using the following three
% helper functions: simulateAllSamples, simulateOneSample,
% simulateOneSubject. 

% The number of simulated samples, subjects per sample, and random seed are
% specified in this current script. Other simulation parameters (e.g., number
% of simulated trials, mean amplitude for each emotion condition) are
% specified in the helper functions. 

% Compared to the LME_05_MeasureERPs.m tutorial script, mean amplitude
% values for all subjects are exported in one file in long format to 
% reduce processing time. The LMESimulation_03_OrganizeDataFiles.R is then
% used to merge the mean amplitude output files with the subject data logs
% (listing each subject's assigned age group). 

% ***See SimulationScripts README.md available on the LME_MixedEffectsERPTutorial 
% GitHub for additional details: https://github.com/basclab/LME_MixedEffectsERPTutorial/tree/main/SimulationScripts 

% Requirements:    
    % - Needs EEGLAB v 2019_0, ERPLAB v 8.01, SEREEGA v 1.1.0
        % - For more information on EEGLAB, see: Delorme, A. & Makeig, S. (2004).
        %   EEGLAB: An open source toolbox for analysis of single-trial EEG dynamics.
        %   https://sccn.ucsd.edu/eeglab/index.php
        % - For more information on ERPLAB, see: Lopez-Calderon, J., & Luck, S. J.
        %   (2014). ERPLAB: An open-source toolbox for the analysis of event-related
        %   potentials. https://erpinfo.org/erplab/    
        % - For more information on SEREEGA, see: Krol, L. R., Pawlitzki, J., Lotte, F.,
        %   Gramann, K., & Zander, T. O. (2018). SEREEGA: Simulating event-related EEG
        %   activity. https://github.com/lrkrol/SEREEGA
    % - Pediatric Head Atlas release v 1.1, Atlas 1 (0-2 years old) files
        % - Atlas files should be requested and downloaded from: https://www.pedeheadmod.net/pediatric-head-atlases/
        % - The folder containing the atlas files should then be added
        %   to the MATLAB path (via "Home" > "Set Path" > "Add with Subfolders"). 
    % - Filepaths to the following folder:
        % - saveFolder: Folder for saving simulated data output files.
        %   This parent folder has two subfolders: MeanAmpOutput_PreMerge
        %   and SubjectDataLog, which are used for saving the corresponding
        %   mean amplitude output files and subject data logs (see Outputs
        %   section below). 
    % - Variables used to specify data simulation parameters:
        % - sampleN: Number of simulated samples.
        % - sampleStart: Sample ID for first simulated sample (e.g., the first
        %   simulated sample will have an ID of #1).
        % - subjectN: Number of simulated subjects per sample.
    % - (Specified in simulateOneSubject function) Filepath to the following 
    %   file used during processing: 
        % - binDescriptorFilename: File specifying each bin's number, label, 
        %   and 5-digit event markers. This file is created by the
        %   LMESimulation_01_CreateBinDescriptorFile.m script. 
          
% Script Functions:
    % 1. Define simulation parameters
    % 2. Simulate data with helper functions
    
% Outputs:
    % - NOTE: All output files are generated and saved in the
    %   simulateOneSample function. Compared to the
    %   LME_05_MeasureERPs.m tutorial script, the setNaNForEmptyBins
    %   function is not required because missing trials have not been
    %   generated at this step of the simulation yet. 
    % - Mean amplitude .txt files with one mean amplitude value per bin/
    %   channel/subject. There is one file for each simulated sample.
    %   Each file contains the following columns:
        % - value: The mean amplitude for this simulated subject’s specified
        %   bin and channel. This value is extracted from C4 (corresponding 
        %   to E104 of the EGI HydroCel GSN 128-channel montage) over a 
        %   300-500 ms time window. 
        % - chindex: The channel number (e.g., channel #2 corresponds to 
        %   E104 in this simulation).
        % - chlabel: The label for this channel (e.g., E104).
        % - bini: A number generated by ERPLAB when concatenating ERP
        %   data files across each sample's subjects. NOTE: This bin number
        %   does NOT correspond to the bin number in the bin descriptor
        %   file (created in LMESimulation_01_CreateBinDescriptorFile.m)
        %   and is NOT used for subsequent processing. 
        % - binlabel: A label composed of [SUBJECTID]_:_[trial-specific bin label].
        %   The trial-specific bin label corresponds to the labels from the
        %   bin descriptor file (created in LMESimulation_01_CreateBinDescriptorFile.m).
        %   This label is used to identify subject ID and stimuli-related information in
        %   LMESimulation_03_OrganizeDataFiles.R. 
        % - ERPset: This column is intentionally empty because it is NOT needed 
        %   for identifying subject ID (see binlabel column above). 
    % - Subject data log .txt files with one row corresponding to each subject.
    %   There is one file for each simulated sample. Each file contains the 
    %   following columns:
        % - SUBJECTID: Simulated subject ID (e.g., 01, 02, …).
        % - age: Simulated age group (i.e., youngerAgeGroup, olderAgeGroup).
    % - (Optional) .erp files containing the trial-level waveforms for all
    %   subjects in a sample. There is one file for each simulated sample
    %   and they are saved directly in the saveFolder specified above (not
    %   in a subfolder). These files are useful for visualizing waveforms
    %   or troubleshooting. 

% Copyright 2021 Megan J. Heise, Serena K. Mon, Lindsay C. Bowman
% Brain and Social Cognition Lab, University of California Davis, Davis, CA, USA.

% Permission is hereby granted, free of charge, to any person obtaining a 
% copy of this software and associated documentation files (the "Software"),
% to deal in the Software without restriction, including without limitation
% the rights to use, copy, modify, merge, publish, distribute, sublicense, 
% and/or sell copies of the Software, and to permit persons to whom the
% Software is furnished to do so, subject to the following conditions:

% The above copyright notice and this permission notice shall be included 
% in all copies or substantial portions of the Software.

% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.

%% DATA ENVIRONMENT

% Specify folder location for saving output files. This parent folder has
% two subfolders (MeanAmpOutput_PreMerge and SubjectDataLog; see Outputs
% section above).
saveFolder = 'C:\Users\basclab\Desktop\LMESimulation';

%% 1. DEFINE SIMULATION PARAMETERS

sampleN = 50; % Number of simulated samples

% Sample ID for first simulated sample (e.g., sample #1). This variable is 
% used when multiple computers are running separate simulations (e.g., computer
% 1 simulates samples #1-500 and computer 2 simulates samples #501-750). 
sampleStart = 1; 

% Number of simulated subjects per sample. In this simulation, this variable is
% even because we are dividing half of the subjects into the younger and
% older age groups (see simulateOneSample function for more information).
subjectN = 50; 

rng(1,'twister'); % Set random seed

%% 2. SIMULATE DATA WITH HELPER FUNCTIONS

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab; % Initialize EEGLAB

% Call helper function with specified input arguments (see comments in
% simulateAllSamples function for more information)
simulateAllSamples(sampleN, sampleStart, subjectN, saveFolder);